#!/usr/bin/env bash


#*************************************************************************************************************#
#                                                                                                             #
#                                         HERE BE DRAGONS                                                     #
#                                                                                                             #
#*************************************************************************************************************#

# Get the period after which certs should be renewed
days=$(php "/root/.le2ispc/le2ispc.conf.php")
if [[ ! "${days}" -gt 0 ]]; then
   echo "Couldn't get the correct amount of days after which certs should be renewed."
   echo "Please check your config and retry."
   exit 1
fi


# Check parameter input
while getopts ":thd:" opt; do
  case $opt in
    d)  days="${OPTARG}"
        ;;
    t)  testrun="yes"
        ;;
    h)  echo "Usage: ${0} [-h|-d DAYS|-t]"
        echo "-h: print help"
        echo "-d: DAYS: Use this switch to specifiy a different renewal interval (only for one run)"
        echo "-t: make dry-run, print the domains that would be renewed"
        exit 0
        ;;
    \?) echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    :)  echo "Option -$OPTARG requires an argument (number of days)." >&2
        exit 1
        ;;
  esac
done

if [[ "${testrun}" = "yes" ]]; then
    echo "The following domains would have been renewed since ${days} days have passed."
    find "/etc/letsencrypt/live/"* -type d -mtime +"${days}" -exec bash -c 'domain=${1##*/}; echo "${domain}"' _ {} \;
else
    find "/etc/letsencrypt/live/"* -type d -mtime +"${days}" -exec bash -c 'domain=${1##*/}; le2ispc "${domain}"' _ {} \;
fi
