#!/usr/bin/env bash

mode="${1}"

confDir="/root/.le2ispc"

removeApache ()  {
    a2disconf "letsencrypt-webroot.conf"
    if [[ -d "/etc/apache2/conf-available/letsencrypt-webroot.conf" ]]; then
        rm "/etc/apache2/conf-available/letsencrypt-webroot.conf"
    fi
    systemctl reload apache2
}

removeSymlink () {
    if [[ -f "/usr/local/bin/le2ispc" ]]; then
        rm "/usr/local/bin/le2ispc"
    fi
}

removeAll () {
    removeSymlink
    if [[ -d "${confDir}" ]]; then
        rm -Rf "${confDir}"
    fi
}


case "${mode}" in
    "all")      echo "Removing symlink and config file"
                removeApache
                removeAll;
                echo "Removal done"
                ;;
    "symlink")  echo "Removing symlink"
                removeApache
                removeSymlink
                echo "Removal done"
                ;;
    *)          echo "Usage: ./uninstall all|symlink"
                echo "    'all' will remove the symlink and the config file"
                echo "    'symlink' will only remove the symlink in '${confDir}'"
                echo "The files in here won't be removed and must be manually removed."
                ;;
esac